### ISSUE TITLE
Распарсіць назвы арганізацый і дату адказу

### ISSUE THREAD

**Issue by gsk990** [opendataby/115#13]
напрыклад, 115.бел/problem/16628

portia spider?
згенерыраваць спіс ID заявак і парсіць?

**Comment by gsk990** [comment]
portia не працуе з гэтымі старонкамі, выдае 0 вынікаў
спрабую з google spreadsheet importxml, першая спроба: не атрымалася, зашмат запытаў, скрэйпер завіс
другая спроба: 
згенерыраваць спіс ID заявак БЕЗ арганізацый, зараз дадаю ў шыт, пачынаю парсіць па частках, па 1000-5000 заявак

усяго 63355 заявак без арганізацый
[list-of-problems-without-organizations.txt](https://github.com/opendataby/115/files/2331710/list-of-problems-without-organizations.txt)

**Comment by gsk990** [comment]
вось тут будзе ЦСВ з вынікамі парсінга:
https://docs.google.com/spreadsheets/d/e/2PACX-1vTrjXULnyBZNQ7KK_uoWbQhhis58_YhHTJeFsiyLVvI3aJ2fbnoZEW8r2ruuxfshWNAZa5CwHHOleXW/pub?gid=0&single=true&output=csv

вось скрэйпінг шыт
https://docs.google.com/spreadsheets/d/1sntx1UzE97ggzYo27m4qWKYUb5WgBGcfqxdKr32LhUQ/edit#gid=0

**Comment by gsk990** [comment]
new scraping sheet -> CSV export https://docs.google.com/spreadsheets/d/e/2PACX-1vTrjXULnyBZNQ7KK_uoWbQhhis58_YhHTJeFsiyLVvI3aJ2fbnoZEW8r2ruuxfshWNAZa5CwHHOleXW/pub?gid=0&single=true&output=csv

**Comment by nickolayka** [comment]
что-то не работает (

**Comment by gsk990** [comment]
Я вось спрабую праз google spreadsheets - учора пачау па новай, да канца дня учора там было распаршана 3000 з 63000 радкоу з дадзенымi. Можа сёння яшчэ15000 радкоу атрымаецца.Дадаткова я збраю дату адказу I ацэнкi y баллах‎ (ад 1 да 5) што ставяць юзеры выканауцам.‎Працэс аказауся нечакана доугiм, але хутка думаю ужо скончу.‎Але з бонусау гэтага працэса - будзем мець абноулены датасет з мапай усх ЖЭСау мiнска для опендата.бай, у нас гэта быу адзiн з самых папулярных датасэтау заусёды на сайце.

**Comment by gsk990** [comment]
працэс ідзе, але з паўзамі. вось частковы датасет, 3187 заявак з арганізацыямі - з тых, у каторых не было прыпісаных арганізацый. Фармат - ХТМЛ спіс.
[harvested_results-3187.txt](https://github.com/opendataby/115/files/2342322/harvested_results-3187.txt)

**Comment by gsk990** [comment]
на сёння - 4250 заявак распарсілі

**Comment by gsk990** [comment]
4792!

**Comment by gsk990** [comment]
5585

**Comment by gsk990** [comment]
6000

**Comment by gsk990** [comment]
6350

**Comment by gsk990** [comment]
7204

**Comment by gsk990** [comment]
7400

**Comment by gsk990** [comment]
7725

**Comment by gsk990** [comment]
7979

**Comment by gsk990** [comment]
9441

**Comment by gsk990** [comment]
11659

**Comment by gsk990** [comment]
12870

**Comment by gsk990** [comment]
13428

**Comment by gsk990** [comment]
14312

**Comment by gsk990** [comment]
14715

**Comment by gsk990** [comment]
16418

**Comment by gsk990** [comment]
16685

**Comment by gsk990** [comment]
17657

**Comment by gsk990** [comment]
18386

**Comment by gsk990** [comment]
22581

**Comment by gsk990** [comment]
23000

**Comment by gsk990** [comment]
25626

**Comment by gsk990** [comment]
25767

**Comment by gsk990** [comment]
26263

**Comment by gsk990** [comment]
26659

**Comment by gsk990** [comment]
31953

**Comment by gsk990** [comment]
32446

**Comment by gsk990** [comment]
34856

**Comment by gsk990** [comment]
41257

**Comment by gsk990** [comment]
41364

**Comment by gsk990** [comment]
43991

**Comment by gsk990** [comment]
45739

**Comment by gsk990** [comment]
46740

**Comment by gsk990** [comment]
49042

**Comment by gsk990** [comment]
53650

**Comment by gsk990** [comment]
54658

**Comment by gsk990** [comment]
54808

**Comment by gsk990** [comment]
55390

**Comment by gsk990** [comment]
56726

**Comment by gsk990** [comment]
57629

**Comment by gsk990** [comment]
59390

**Comment by gsk990** [comment]
60642!

**Comment by gsk990** [comment]
65896

**Comment by gsk990** [comment]
68654

**Comment by gsk990** [comment]
усё распаршана і запісана ў #8
