### ISSUE TITLE
Тех.обслуживание Python парсера Октябрь 2019

### ISSUE THREAD

**Issue by abitrolly** [opendataby/115#22]
В связи с новой статьёй https://realt.onliner.by/2019/10/11/115-bel-6 возник повод причесать парсер. Вернее, в канале https://t.me/Minsk_115 мне сказали, что на https://115.netlify.com нет данных за 2019 год, а потому уже оказалось, что статья вышла.

Сначала я думал, что надо пнуть парсер, т.к. сбор информации происходит только по коммиту (#21), а нннет - он [на самом деле отвалился](https://app.netlify.com/sites/115/deploys/5da43f8ed59727f914658727).

Из лога, видно, что используется древний Python 3.4.

* [x] [настроить Netlify](https://www.netlify.com/docs/build-settings/#build-image-selection) на свежий Python

Но даже без него, локально Python 3.7 тоже валится. С другой ошибкой, но тем не менее. Вряд ли таким макаром можно получить свежие данные.

* [x] исправить вылетающий `./001-order.py -f` для начала
```
✗ ./001-order.py -f
Traceback (most recent call last):
  File "./001-order.py", line 78, in <module>
    content, cookie = get_page(URL, '001-in-seed.txt', force)
  File "./001-order.py", line 38, in get_page
    req = urlopen(url)
  File "/usr/lib64/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
...
    self.putheader(hdr, value)
  File "/usr/lib64/python3.7/http/client.py", line 1217, in putheader
    values[i] = one_value.encode('latin-1')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 4-6: ordinal not in range(256)
```
Этого пока хватит. Потом можно будет добавить историю прямо на GitHub, потому что 115.бел по-ходу подчищает старые записи (хвалёный Oracle видать, не выдерживает :D) , прикручивать https://molamola.by (начал я это дело в 19:00, чтобы было что считать по рейту :D), править "дизайн", добавлять города, описание полей и [далее по списку](https://github.com/opendataby/115/issues).

* [x] восстановить исторические данные старше года и запихать их в [./docs](./docs)

---

На самом деле нас есть два парсера.

1. Этот https://github.com/opendataby/115 который сделал я, потому что 115.бел жадничает и на предоставляет открытые данные
2. Альтернативная версия на Ruby от @jekhor https://github.com/jekhor/115 потому что я криворукий, а он Python не знает :D - говорят, она работает лучше и получает больше данных

Но пока надо привести эту версию в порядок.

**Comment by abitrolly** [comment]
Переключение Netlify с Ubuntu 14 на Ubuntu 16 апнуло Python с 3.4 всего до 3.5. Зато [ошибка теперь совпадает](https://app.netlify.com/sites/115/deploys/5da4b30f4f49ca0008636b0b) с локальным Python 3.7.

**Comment by abitrolly** [comment]
Ошибка из-за того, что к http://115.бел наконец-то прикрутили https, хоть и криво, так что он [почти не от чего не защищает](https://www.ssllabs.com/ssltest/analyze.html?d=115.xn--90ais), причём по-ходу с дорогим сертификатом от DigiCert, а не бесплатным Let's Encrypts.

Теперь http://115.бел редиректит на https://115.бел а Python 3.7 никто не научил обрабатывать редиректы на адреса не в латинской раскладке (IDNA). Проблема решена в библоитеке `requests`, но здесь я её не юзаю https://github.com/psf/requests/commit/868cd3d1cb86cf1b657e16dd00aa66d3ceb7fc1e#commitcomment-35494913

К сожалению, исправление URL на правильный, ничего на даёт, потому что 115.бел купили дорогущий Oracle и теперь заставляют всех страдать через его Apex. Надо переделывать парсер заново. Радует, что теперь, кроме https, на сайте есть кошерный OpenStreetMap, который, конечно, лучше работает с PostrgreSQL, но научить 115.бел PostrgreSQL некому, а курсы по Oracle работникам 115.бел нравятся.

**Comment by abitrolly** [comment]
Пока всё что можно сделать, это залить старый архив до июня этого года в `./docs`.

**Comment by jekhor** [comment]
Смешались в кучу кони, люди...
https там некошерный, кстати.
Что такое "есть OpenStreetMap?" Подложка и так была осм, а веб-движок у них унылый оракловский.
Переделывать парсер уже бесполезно, потому что закрыт доступ к детализации чужих заявок, сейчас только свои можно смотреть, остальные только точками с категориями.

**Comment by abitrolly** [comment]
@jekhor ну неохота отдельные сущности плодить в трекере. Много времени кушает людей от коней отделять. Раньше Google Maps был.

Движок да, унылей некуда. Знаешь, что он на фронте использует? Ajax - [добро пожаловать в 90е](https://en.wikipedia.org/wiki/Ajax_(programming)). React, Angular, vue - не, не слыхали. :D Хорошие сейлзы у Оракла, что тут можно сказать.

По заявкам нет доступа к id пользователя, даже анонимизированному. Без этого id невозможно сделать топчик самых активный пользователей, да и вообще социальный аспект теряется. Во времена GitHub и соц.сетей это шаг назад, ятакщитаю. Профили должны быть публичны, а что там показывать пусть каждый сам решает.

Унылость ещё в том, что нельзя дать прямую ссылку на заявку, только перейти через поиск. Может 115.бел их специательно так сделал, и втихую неугодных удаляет? Без ссылок то не докажешь. Но хотя токен в ссылке неживой для другой сессии, в анонимной сессии детали заявок в районе всё же открываются. Только тормозят. Потому что нас там нет. :D

**Comment by abitrolly** [comment]
Вылетающий `./001-order.py -f` исправлен в 9329e69, но толку от этого никакого - [урлы не те](#23).

**Comment by abitrolly** [comment]
Не слушают 115.бел отца мировой паутины - https://www.w3.org/Provider/Style/URI

**Comment by abitrolly** [comment]
Запихал последние цээсвэхи с июля 2019 в https://github.com/opendataby/115/tree/master/docs Из-за #17 надо из обогатить данными прошлый сканов, и заархивировать всё.

**Comment by abitrolly** [comment]
Сделал всё что мог. Жаль некому счёт выставить на 6 часов. :D
