### ISSUE TITLE
Добавить возможность скачать весь датасет одним файлом

### ISSUE THREAD

**Issue by gsk990** [opendataby/115#3]
Для многих людей смерджить отдельные файлы - это непростая задача сама по себе, а ещё есть у некоторых на виндоус глюки с кодировками при открывании ЦСВ с русским текстом, и необходимость мерджить куски, и для каждого решать проблему с кодировкой это нехилый квест :)

спасибо!

**Comment by gsk990** [comment]
круто, скачивается, но почему-то только на сервере скачиваются и лежат файлы за последние 12 месяцев, с 09-2016, а не с 11-2015. Это связано с данной задачей или это отдельная фича/баг? спасибо! @abitrolly

**Comment by abitrolly** [comment]
Отдельный баг. На карте 115.бел в меню только последние 12 месяцев.

**Comment by abitrolly** [comment]
Можно захардкодить первый месяц год и плясать от него вместо того, чтобы 115.бел опрашивать.

**Comment by gsk990** [comment]
я думаю да, нужно захардкодить первый месяц-год (2015-11).

кстати, в системе добавился Витебск, а АПИ про витебские данные что-нибудь
знает?

**Comment by mrR2D2** [comment]
Сделал мердж всех .csv в один, можем закрывать :)

**Comment by abitrolly** [comment]
5c1dd60f

Теперь логика размазана ещё через python и bash. Лучше оставлять всё на python, для людей, которые до сих пор всякий виндовз пользуют.

**Comment by abitrolly** [comment]
https://github.com/opendataby/115/blob/gh-pages/008-build.py надо править.

**Comment by abitrolly** [comment]
>  на сервере скачиваются и лежат файлы за последние 12 месяцев, с 09-2016, а не с 11-2015

@gsk990 можешь отдельный баг на это завести?

**Comment by abitrolly** [comment]
@mrR2D2 красивый хак, но я переписал всё на питоне. :D

Проверьте лишний раз, что opendata-115-all.csv из https://115.netlify.com/dataset-115.bel-20170925-115726.zip валидный. Там пустых строк нет или слишком длинных. Я только проверил, что заголовки не повторяются.

**Comment by abitrolly** [comment]
> кстати, в системе добавился Витебск, а АПИ про витебские данные что-нибудь
знает?

https://github.com/opendataby/115/commit/531729a8bb837e05c8a8d5f8b660175ca3a039c4#diff-78951a40a2d66d2679f74a661dfae9fdR1297
Пока это всё, что известно. Добавляй тикет. ;)
