### ISSUE TITLE
на сервере доступны данные только за последние 12 месяцев, с 09-2016, а не с 11-2015

### ISSUE THREAD

**Issue by gsk990** [opendataby/115#5]
на сервере скачиваются и лежат файлы за последние 12 месяцев, с 09-2016, а не с 11-2015

(из комментов в баге №3) - https://github.com/opendataby/115/issues/3#issuecomment-328257575)

**Comment by abitrolly** [comment]
Пофиксил. Проверяй - https://115.netlify.com/
